Spring Boot 3 and JDK 21
adorsys/keycloak-config-cli pull request #1001
Opened 2024-03-13 22:26 UTC by jonasvoelcker

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

2024-03-26 08:04 UTC, st3v0rr commented
Review looks good. Before we merge it...
We will drop support for any Java version besides Java 21.
Last chance for objections until tonight :-)

2024-03-28 06:32 UTC, st3v0rr commented on .github/workflows/ci.yaml
> +          - KEYCLOAK_VERSION: 22.0.5
@jonasvoelcker since only the tests fail with this 22.0.5 version can you maybe give it a try with the old version?

2024-03-28 06:33 UTC, st3v0rr commented
As soon as the issue with keycloak 22 tests is fixed I will merge it and perform a release.

2024-06-01 13:26 UTC, francis-pouatcha commented on src/test/java/de/adorsys/keycloak/config/test/util/SubGroupUtil.java
> +        if (!CollectionUtils.isEmpty(groupRepresentation.getSubGroups())) {
Any rationale behind this change?

2024-06-01 14:07 UTC, francis-pouatcha requested changes

2024-06-01 14:07 UTC, francis-pouatcha commented on src/main/java/de/adorsys/keycloak/config/service/ClientPoliciesImportService.java
> +            // client-profile profiles must be imported before client-profile policies
```suggestion
        if (VersionUtil.ge(keycloakProvider.getKeycloakVersion(), "20")) {
            // client-profile profiles must be imported before client-profile policies
```

2024-06-01 14:07 UTC, francis-pouatcha commented on src/main/java/de/adorsys/keycloak/config/service/ClientPoliciesImportService.java
> +import org.apache.commons.lang3.StringUtils;
```suggestion
import de.adorsys.keycloak.config.util.VersionUtil;
```

2024-06-01 22:07 UTC, merged