Improve managed resources
adorsys/keycloak-config-cli pull request #1188
Opened 2024-11-08 10:31 UTC by Motouom

**What this PR does / why we need it**: Improve documentation of managed resources

**Which issue this PR fixes** #826 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

2024-11-12 16:03 UTC, AssahBismarkabah requested changes

2024-11-12 16:03 UTC, AssahBismarkabah commented on docs/MANAGED.md
> -If `import.remote-state.enabled` is set to `true` (default value), keycloak-config-cli will purge only resources they created before by keycloak-config-cli. If `import.remote-state.enabled` is set to
Hi @Motouom  why remove this section ?

2024-11-12 16:05 UTC, AssahBismarkabah commented
@Motouom  please resolve the conflicts
thank you

2024-11-15 15:29 UTC, Motouom commented
> @Motouom please resolve the conflicts thank you

@AssahBismarkabah  thank you, i have solved  the issue

2024-11-21 08:38 UTC, AssahBismarkabah commented on docs/MANAGED.md
> +# Resource Management in keycloak-config-cli
hi @Motouom  please aligned the tag with ## and ### for subsections, also please just keep the tag 1 as Resource  management

2024-11-29 13:13 UTC, AssahBismarkabah approved these changes

2024-11-29 13:13 UTC, merged