[#217] added removing client option
adorsys/keycloak-config-cli pull request #219
Opened 2020-10-09 07:54 UTC by ArtemZip

2020-10-09 16:21 UTC, jkroepke requested changes

2020-10-10 17:47 UTC, jkroepke commented on src/main/java/de/adorsys/keycloak/config/service/ClientImportService.java
> +    private static final Set<String> defaultClients = new HashSet<>(Arrays.asList(
It's possible to use this list?

https://github.com/keycloak/keycloak/blob/d46620569ad2a560b6acb5ba737ac5f0dd2b077e/server-spi-private/src/main/java/org/keycloak/models/Constants.java#L43

2020-10-10 18:13 UTC, jkroepke commented on src/main/java/de/adorsys/keycloak/config/service/ClientImportService.java
> +    private static final Set<String> defaultClients = new HashSet<>(Arrays.asList(
Hm. `ACCOUNT_CONSOLE_CLIENT_ID `is missing, too.

I'm talking about changes like this: https://github.com/keycloak/keycloak/pull/6501/files#diff-547facf35708153ee8f50c2258d6c668R36

If there is a new default client, no one should notice it.

2020-10-10 18:19 UTC, jkroepke commented on src/main/java/de/adorsys/keycloak/config/service/ClientImportService.java
> +    private static final Set<String> defaultClients = new HashSet<>(Arrays.asList(
Alternatively, we could detect a default a by pattern:

```
  "clients": [
    {
      "id": "229070b6-9ee0-4995-a3bd-1f658f53b22f",
      "clientId": "account",
      "name": "${client_account}",
    },
    {
      "id": "2f23f980-846e-43b3-9688-829afaec2da2",
      "clientId": "account-console",
      "name": "${client_account-console}",
    },
    {
      "id": "59e97774-c985-4f92-89e6-b0cef34652a4",
      "clientId": "admin-cli",
      "name": "${client_admin-cli}",
    },
    {
      "id": "8ca2f732-2ea6-45c8-966b-a4fc99ff278e",
      "clientId": "broker",
      "name": "${client_broker}",
    },
    {
      "id": "4a77b1c4-068b-4fa1-8559-a433773fc06c",
      "clientId": "security-admin-console",
      "name": "${client_security-admin-console}",
    }
  ],
```

If "${client_" + clientID + }" == name, then there is a high chance that the client is a default client.

OR

existing-realm + "-realm" == clientId, then it's a client on master realm for a specific realm.

Additionally a new test could cover this, by creating a realm, get all clients. do a import with empty array and compare the list of clients before and after import.

2020-10-10 18:20 UTC, jkroepke commented
I'm confused why the tests failed in CI but are success on my local machine.

2020-10-10 19:23 UTC, jkroepke commented on src/test/java/de/adorsys/keycloak/config/service/ImportManagedClientsFullIT.java
> +    private static final String REALM_NAME = "realmWithClients";
Please use an other realm name here. Each realm should be unique for every test class to avoid race conditions.

2020-10-13 07:20 UTC, ArtemZip commented
I don't know why now tests was fixed on versions 9-11

2020-10-14 16:29 UTC, jkroepke commented
Thanks for improvements and sorry for the Merge Conflicts now. I recently add the same functionality for roles.

@ArtemZip I have a question do you have the use case that you are need to delete the default clients?

If not, what about adding state management to clients, too?

https://github.com/adorsys/keycloak-config-cli/blob/master/docs/MANAGED.md#state-management

If enabled Keycloak Config CLI would only delete clients created by self.

2020-10-15 22:37 UTC, jkroepke commented
If you do a rebase, codeclimate should be gone.

2020-10-16 15:32 UTC, jkroepke commented
Sorry for be a little bit strictly. Thanks!

2020-10-16 15:32 UTC, merged