Draft: make user profile feature of keycloak work with keycloak-config-cli
adorsys/keycloak-config-cli pull request #766
Opened 2022-08-05 13:23 UTC by srose

**What this PR does / why we need it**:
Keycloak export does not contain the User Profile JSON Definiton.
It would be great to have the Profile Definition work with keycloak-config-cli

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
No issue yet

**Special notes for your reviewer**:
Want to discuss the solution and possible tests.

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

2022-09-19 18:03 UTC, srose commented
Would be great to have some feedback...

2022-10-26 13:49 UTC, thomasdarimont requested changes
Looks good so far, some minor remarks inline.

2022-10-26 13:49 UTC, thomasdarimont commented on src/test/java/de/adorsys/keycloak/config/service/ImportUserPorfile.java
> +public class ImportUserPorfile extends AbstractImportIT {
```suggestion
public class ImportUserProfile extends AbstractImportIT {
```

2022-10-26 13:49 UTC, thomasdarimont commented on src/test/java/de/adorsys/keycloak/config/service/ImportUserPorfile.java
> +    ImportUserPorfile() {
```suggestion
    ImportUserProfile() {
```

2022-10-26 13:49 UTC, thomasdarimont commented on src/main/java/de/adorsys/keycloak/config/repository/UserProfileRepository.java
> +        var userProfileEnabled = Boolean.valueOf(realmAttributes.getOrDefault("userProfileEnabled", "false"));
Extract `userProfileEnabled` to constant.

2022-10-26 13:55 UTC, srose commented on src/test/resources/import-files/user-federation/00_create_realm_with_federation.json
> +  "realm": "realmWithProfile",
No, i should do that

2022-10-26 13:56 UTC, srose commented on src/main/java/de/adorsys/keycloak/config/repository/UserProfileRepository.java
> +        var profileDefintionHasNotChanged = userProfileResource.getConfiguration().equals(str);
Nice idea, will change that.

2022-10-27 07:42 UTC, srose commented
@thomasdarimont please have a look, i am still not sure if its complete. tests could be improved anyhow and i will continue on them.

2022-10-29 09:03 UTC, thomasdarimont requested changes

2022-10-29 09:03 UTC, thomasdarimont commented on src/main/java/de/adorsys/keycloak/config/repository/UserProfileRepository.java
> +        String profileResourceConfiguration = Optional.ofNullable(userProfileResource.getConfiguration()).orElse("");
```suggestion
        var profileResourceConfiguration = Optional.ofNullable(userProfileResource.getConfiguration()).orElse("");
```

2022-10-29 09:08 UTC, thomasdarimont requested changes
Looks good so far, some remarks:

- Use `var` where appropriate
- Document profile support in https://github.com/adorsys/keycloak-config-cli/blob/main/docs/FEATURES.md
- Fix test failures
- Add minimal profile example config as yaml to https://github.com/adorsys/keycloak-config-cli/tree/main/contrib/example-config

Example config:
```yaml
realm: acme-profile
displayName: "Acme Profile"
enabled: true

attributes:
  userProfileEnabled: "true"

userProfile:
  - name: username
    displayName: "${username}"
    validations:
      length:
        min: 3
        max: 255
      username-prohibited-characters: { }
  - name: email
    displayName: "${email}"
    validations:
      email: { }
      length:
        max: 255
  - name: firstName
    displayName: "${firstName}"
    required:
      roles:
        - user
      scopes: [ ]
    permissions:
      view:
        - user
        - admin
      edit:
        - user
        - admin
    validations:
      length:
        max: 255
      person-name-prohibited-characters: { }
    selector:
      scopes: []
  - name: lastName
    displayName: "${lastName}"
    required:
      roles:
        - user
      scopes: []
    permissions:
      view:
        - user
        - admin
      edit:
        - user
        - admin
    validations:
      length:
        max: 255
      person-name-prohibited-characters: { }
    selector:
      scopes: []
  - name: phoneNumber
    displayName: "${phoneNumber}"
    permissions:
      view:
        - user
        - admin
      edit:
        - user
        - admin
    required:
      roles: [ ]
      scopes:
        - phone
    selector:
      scopes:
        - phone
```

In upcoming versions, we could have dedicated types for profile attributes to enable syntax validation by keycloak-config-cli.

2022-10-29 09:45 UTC, thomasdarimont requested changes

2022-10-29 09:45 UTC, thomasdarimont commented on src/main/java/de/adorsys/keycloak/config/repository/UserProfileRepository.java
> +        var newValue = mapper.readValue(newPprofileResourceConfiguration, Map.class);
I just gave this a try and noticed that the `ObjectMapper` is not provided as a bean if we run the cli tool.
It seems that other places of the code use the Methods from `de.adorsys.keycloak.config.util.JsonUtil` to use a shared object mapper.

Suggestion use:
```
var currentValue = JsonUtil.fromJson(profileResourceConfiguration, Map.class);
var newValue = JsonUtil.fromJson(newPprofileResourceConfiguration, Map.class);
```

and add a method like:
```
    public static <T> T fromJson(String value, Class<T> type) {
        try {
            return objectMapper.readValue(value, type);
        } catch (JsonProcessingException e) {
            throw new ImportProcessingException(e);
        }
    }
```

After that you can remove the objectMapper constructor parameter and field (and unused imports).

2022-10-29 11:25 UTC, thomasdarimont requested changes

2022-10-29 11:25 UTC, thomasdarimont commented on src/main/java/de/adorsys/keycloak/config/model/RealmImport.java
> +    private List<HashMap<String, Object>> userProfile;
```suggestion
    private List<LinkedHashMap<String, Object>> userProfile;
```
The order of entry should be kept as is.

2022-10-29 11:25 UTC, thomasdarimont commented on src/main/java/de/adorsys/keycloak/config/model/RealmImport.java
> +    public void setUserProfile(List<HashMap<String, Object>> userProfile) {
```suggestion
    public void setUserProfile(List<LinkedHashMap<String, Object>> userProfile) {
```

2022-10-29 11:25 UTC, thomasdarimont commented on src/main/java/de/adorsys/keycloak/config/model/RealmImport.java
> +    public List<HashMap<String, Object>> getUserProfile() {
```suggestion
    public List<LinkedHashMap<String, Object>> getUserProfile() {
```

2022-11-02 11:18 UTC, thomasdarimont commented on src/main/java/de/adorsys/keycloak/config/repository/UserProfileRepository.java
> +        var profileResourceConfiguration = Optional.ofNullable(userProfileResource.getConfiguration()).orElse("");;
```suggestion
        var profileResourceConfiguration = Optional.ofNullable(userProfileResource.getConfiguration()).orElse("");
```

2022-11-02 11:35 UTC, thomasdarimont commented
@st3v0rr I think this PR is quite complete. Would you mind considering this for the next release of keycloak-config-cli?

2022-11-02 22:45 UTC, thomasdarimont commented
@st3v0rr This could be released as a maintenance release 5.3.2

2022-11-07 08:49 UTC, st3v0rr commented
Hi @thomasdarimont and @srose,
PR looks good for me I will do a short test and will release it this afternoon.
Due to the new feature 5.4.0 sounds best for me
Thanks for the contribution I didn't find the time to invest that much in the project in the last 2 months :-/
Greets

2022-11-07 12:01 UTC, merged

2022-11-08 13:04 UTC, thomasdarimont commented
@st3v0rr Thanks for merging!

We know what it means to maintain an OSS library beside a day job :) We're here to support you :)